### ISSUE TITLE
When a parsing error occurs, Landscape exits with 0

### ISSUE THREAD

**Issue by vide** [coinbase/terraform-landscape#89]
When Landscape 0.3.0 finds an unknow mesasge in Terraform output, it prints a `Terraform Landscape: a parsing error occured. Falling back to original Terraform output...` but then it exits with 0. Usually (I'd dare to say always) this is because Terraform failed, so Landscape should exit with an error code too. I rely on Landscape exit codes to do things.

**Comment by sds** [comment]
I don't have enough data to say whether Landscape failures correspond to Terraform failures—my personal experience is that they don't, however.

When dealing with processes in a pipeline, you should be using the [`$PIPESTATUS`](https://unix.stackexchange.com/a/14276) variable (if using `bash`, or [`$pipestatus`](https://unix.stackexchange.com/a/318160) for `zsh`) so you can determine if `terraform` itself failed in the pipeline.

Open to suggestions here, but I think there's an argument to be made for `landscape` not breaking CI runs for teams when it encounters a parsing error or otherwise.

**Comment by udondan** [comment]
Thanks for the pointer to `$PIPESTATUS` @sds

I recently added landscape to our CI and now was wondering about the exit code in case of locked statefile. 🤦‍♂️

**Comment by tdmalone** [comment]
You can also use `set -o pipefail` at the top of your CI Bash scripts (which is probably best practice, anyway).

I'd prefer that Landscape _doesn't_ exit with non-zero if it has a parsing error. Considering it falls back to the main Terraform output, I don't consider it an error I need to know about. It's really more a 'notice'. I'm much more interested in the exit code of the `terraform` command before it.
